### ISSUE TITLE
running XGM wallet error (mac)

### ISSUE THREAD

**Issue by frudas24** [freenetcoder/defis#2]
Hi, error running the gui

I 2020-06-16.09:29:46.904 Grimm Node 100.1.18 (master)
I 2020-06-16.09:29:46.904 Rules signature: 0-a296984f83c062475d11c2c6486bd11d36fba60a223f1995e706cb5d8ff2f665, 444400-e1e6ce8635e3d891175868bdbe4cc92fa56f346e47d21855c4c6399ccd43e761
Illegal instruction: 4

**Comment by freenetcoder** [comment]
What macOS version?
What Qt version you use?
openssl, boost and cmake versions?
P.s. Also please running ur pre-build version from releases for mac. Is it launching normally?

**Comment by frudas24** [comment]
macOS: catalina 10.15.5
qt: 5.11
openssl: openssl@1.1
boost: stable 1.72.0
cmake: stable 3.17.3
i have grimm instaled.
never pre-build before.

**Comment by freenetcoder** [comment]
try use gpu_on when call cmake:
cmake -DXGM_USE_GPU=On -DCMAKE_BUILD_TYPE=Release . && make -j4

**Comment by frudas24** [comment]
./defis-wallet/XGM\ Wallet

<img width="1308" alt="Captura de Pantalla 2020-06-18 a la(s) 11 32 38 a  m" src="https://user-images.githubusercontent.com/5379050/85047426-6d2a9600-b157-11ea-9db9-ec434fa4a3b0.png">
not working :(

**Comment by freenetcoder** [comment]
Can you download wallet from https://github.com/freenetcoder/defis/releases/tag/v100.1.5 and launch? Is there are any errors for you?

**Comment by frudas24** [comment]
Work perfectly 👍
